name: Checks

on: [push]

jobs:
  test-lints:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub 
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOKCERHUB_TOKKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"